# Generated by Django 5.2.5 on 2025-08-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='color',
            field=models.CharField(default='#22c55e', max_length=7),
        ),
        migrations.AddField(
            model_name='habit',
            name='goal_count',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='habit',
            name='goal_period',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10),
        ),
        migrations.AddField(
            model_name='habitlog',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
