# Generated by Django 5.2.5 on 2025-08-29 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_archived_habit_color_habit_goal_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='goal_period',
            new_name='goal_type',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='color',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='goal_count',
        ),
        migrations.RemoveField(
            model_name='habitlog',
            name='note',
        ),
        migrations.AddField(
            model_name='habit',
            name='goal_target',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='habit',
            name='target_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10),
        ),
        migrations.CreateModel(
            name='HabitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='habits.habit')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('habit', 'date')},
            },
        ),
    ]
