# Generated by Django 5.2.3 on 2025-09-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_rename_goal_period_habit_goal_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
